services:
  order-service:
    build: .
    container_name: order-service
    ports:
      - "5002:5002"
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB_NAME: ecommerce
      DB_USER: postgres
      DB_PASSWORD: postgres
