apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: dev
data:
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: ecommerce
  PRODUCT_SERVICE_URL: http://product-service:5001
